---

- name: Deploy systemd service units
  template:
    src: systemd.service.j2
    dest: "/etc/systemd/system/rest-server-{{ item.path | hash('sha1') | truncate(6, True, '') }}.service"
  with_items: '{{ restic_rest_repos }}'
  notify: rest-server restart
  become: true

- name: Enable service units
  systemd:
    enabled: yes
    daemon_reload: yes
    name: "rest-server-{{ item.path | hash('sha1') | truncate(6, True, '') }}.service"
  with_items: '{{ restic_rest_repos }}'
  when: restic_rest_target_enable
  become: true

- name: Deploy systemd target
  become: true
  template:
    src: systemd.target.j2
    dest: "/etc/systemd/system/rest-server.target"

- name: Ensure service started
  systemd:
    state: started
    daemon_reload: yes
    name: 'rest-server.target'
  become: true
