---
- name: "Create {{ restic_rest_args_path }}"
  ansible.builtin.file:
    path: "{{ restic_rest_args_path }}"
    owner: "{{ restic_rest_user }}"
    group: "{{ restic_rest_group }}"
    state: directory
    mode: 0755
  become: true
  tags: restic_rest

- name: Template service
  ansible.builtin.template:
    src: service.j2
    dest: "/etc/systemd/system/{{ restic_rest_service }}"
    mode: 0644
  become: true
  notify: restart rest-server
  tags: restic_rest

- name: Enable service
  ansible.builtin.systemd:
    enabled: true
    name: "{{ restic_rest_service }}"
  become: true
  tags: restic_rest
