---
- name: Install python-passlib
  ansible.builtin.package:
    name: python3-passlib
    state: present
  become: true
  tags: restic_rest

- name: "Delete {{ restic_rest_args_path }}/.htpasswd"
  ansible.builtin.file:
    path: "{{ restic_rest_args_path }}/.htpasswd"
    state: absent
  become: true
  tags:
    - restic_rest
    - restic_rest_accounts_reset
  when: "'restic_rest_accounts_reset' in ansible_run_tags"

- name: "Add accounts to {{ restic_rest_args_path }}/.htpasswd"
  community.general.htpasswd:
    path: "{{ restic_rest_args_path }}/.htpasswd"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    owner: "{{ restic_rest_user }}"
    group: "{{ restic_rest_group }}"
    crypt_scheme: "{{ restic_rest_htpasswd_crypt_scheme }}"
    mode: 0640
  loop: "{{ restic_rest_accounts }}"
  no_log: "{{ restic_rest_no_log }}"
  become: true
  tags:
    - restic_rest
    - restic_rest_accounts_reset
  when: restic_rest_accounts is defined
