---

- name: set internal variable platform-suffix
  set_fact:
    _platform_suffix: 'linux-amd64'
  when: ansible_userspace_bits == '64'

- name: set internal variable platform-suffix
  set_fact:
    _platform_suffix: 'linux-386'
  when: ansible_userspace_bits == '32'

- name: Download client binary
  get_url:
    url: '{{ restic_rest_url }}'
    dest: '/tmp/'
  register: get_url_restic

- name: Decompress the binary
  shell: "gzip -dc {{ get_url_restic.dest }} > {{ restic_install_path }}/{{ restic_rest_binary }}-{{ restic_rest_v }}"
  args:
    creates: '{{ restic_install_path }}/{{ restic_rest_binary }}-{{ restic_rest_v }}'

- name: Ensure binary permissions are correct
  file:
    path: '{{ restic_install_path }}/{{ restic_rest_binary }}-{{ restic_rest_v }}'
    mode: '0755'
    owner: 'root'
    group: 'root'

- name: Create symlink
  file:
    path: '{{ restic_install_path }}/{{ restic_rest_binary }}'
    src: '{{ restic_install_path }}/{{ restic_rest_binary }}-{{ restic_rest_v }}'
    state: 'link'
    mode: '0755'
    owner: 'root'
    group: 'root'
