---
- name: set internal variable platform-suffix
  set_fact:
    _platform_suffix: 'linux_amd64'
  when: ansible_userspace_bits == '64'

- name: set internal variable platform-suffix
  set_fact:
    _platform_suffix: 'linux_386'
  when: ansible_userspace_bits == '32'

- name: Decompress the binary
  unarchive:
    src: '{{ restic_rest_url }}'
    dest: "{{ restic_install_path }}"
    remote_src: true
    creates: '{{ restic_install_path }}/{{ restic_download_dir }}/{{ restic_rest_binary }}'
  become: true

- name: Ensure binary permissions are correct
  file:
    path: '{{ restic_install_path }}/{{ restic_download_dir }}/{{ restic_rest_binary }}'
    mode: '0755'
    owner: 'root'
    group: 'root'
  when: not ansible_check_mode
  become: true

- name: Create symlink
  file:
    path: '{{ restic_install_path }}/{{ restic_rest_binary }}'
    src: '{{ restic_install_path }}/{{ restic_download_dir }}/{{ restic_rest_binary }}'
    state: 'link'
    mode: '0755'
    owner: 'root'
    group: 'root'
  when: not ansible_check_mode
  become: true
