---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
      become: true
  tasks:
    - name: "Include itsnotgoodname.restic_rest"
      ansible.builtin.import_role:
        name: "itsnotgoodname.restic_rest"

