---
- name: Verify
  hosts: all
  gather_facts: false
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: Collect facts about system services
      ansible.builtin.service_facts:
      register: services_state

    - name: Assert
      ansible.builtin.assert:
        that:
          - 'services_state.ansible_facts.services["{{ restic_rest_service }}.service"]["state"] == "running"'
          - 'services_state.ansible_facts.services["{{ restic_rest_service }}.service"]["status"] == "enabled"'
